name: Create Tag and Release
on:
  workflow_dispatch:
    inputs:
      TAG:
        required: true
        type: string
        description: Tag to be applied, for example 1.0.0
      CHECKOUT_REF:
        type: string
        description: full commit hash, if none supplied, latest main is taken

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Determine checkout ref
        run: |
          if [[ -z "${{ inputs.CHECKOUT_REF }}" ]]; then
            echo "CHECKOUT_REF=main" >> $GITHUB_ENV
          else
            echo "CHECKOUT_REF=${{ inputs.CHECKOUT_REF }}" >> $GITHUB_ENV
          fi
          
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ inputs.CHECKOUT_REF }}
          path: ./Checkout/${{ github.event.repository.name }}
          
      - name: Check if package.json exists
        run: |
          ls ./Checkout
          cd ./Checkout/${{ github.event.repository.name }}/
          if [ ! -f package.json ]; then
            echo "package.json not found"
            exit 1
          fi
          cd -

      - name: Get package.json
        id: get_package_json
        run: |
          cd ./Checkout/${{ github.event.repository.name }}
          {
            echo 'package_json<<"""'
            echo $(cat package.json)
            echo '"""'
          } >> $GITHUB_OUTPUT
          cd -

      - name: Get needed Data
        id: job_data
        run: |
          version=$(echo "${{ inputs.TAG }}")
          version=$(echo $version | tr '[:upper:]' '[:lower:]')
          echo "version=$version" >> $GITHUB_OUTPUT
          major_version=$(echo $version | cut -d '.' -f 1)
          minor_version=$(echo $version | cut -d '.' -f 2)
          echo "major_version=$major_version" >> $GITHUB_OUTPUT
          echo "minor_version=$minor_version" >> $GITHUB_OUTPUT
          name="${{ fromJson(steps.get_package_json.outputs.package_json).name }}"
          display_name="${{ fromJson(steps.get_package_json.outputs.package_json).displayName }}"
          echo "package_name=$name" >> $GITHUB_OUTPUT
          echo "package_display_name=$display_name" >> $GITHUB_OUTPUT

      - name: Create Packages
        id: create_packages
        uses: VRLabs/VRCTools-Packaging-Action@v1
        with:
          path: './Checkout/${{ github.event.repository.name }}'
          noVcc: true
          outputPath: 'Packages'
          unityReleaseUrl: 'https://github.com/${{ github.repository }}/releases/download/${{ steps.job_data.outputs.version }}/${{ steps.job_data.outputs.package_name }}-${{ steps.job_data.outputs.version }}.unitypackage'
          releaseVersion: '${{ steps.job_data.outputs.version }}'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ steps.job_data.outputs.package_display_name }} ${{ steps.job_data.outputs.version }}"
          files: |
            ${{ steps.create_packages.outputs.unityPackagePath }}
          repository: ${{ github.repository }}
          tag_name: ${{ inputs.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCE_TAG: ${{ steps.job_data.outputs.version }}
          
